
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver #??? ???? ??? jdbc.Driver??
    url: jdbc:mariadb://localhost:3306/spring_borad_db
    username: root
    password: 1234

  jpa:
    database: mysql #mariadb? ?? ? ???.
    #    innoDB ???? ??
    database-platform: org.hibernate.dialect.MariaDBDialect #hibernate : jpa? ?? ??(???)
    #    ???? ???? ??
    generate-ddl: true # ???? ???? ???? ????.
    hibernate:
      #      create??? ?? table? drop? ??(??? ??? ????)
      #      update??? ????? alter? ?? / ??????X, ?????? -> raw DDL??? DB ?????.
      #      validate? ??DB?? ???? check
      #      ????? update ?? validate ?? # ????? ?? create? ?????.
      ddl-auto: create
    #      jpa? ???? ??? ????, ??? console?? ?????
    show-sql: true